image: archlinux/base:latest

before_script:
    - pacman --noconfirm --needed -Syu gcc nasm make clang

stages:
    - build

gcc:
    stage: build
    script:
    - export CC=gcc
    - make

clang:
    stage: build
    script:
    - export CC=clang
    - make
